######################################################################
# Automatically generated by qmake (3.0) Sat Jul 4 18:11:54 2015
######################################################################

TEMPLATE = app
TARGET = Neural
INCLUDEPATH += . src

QT -= core gui
CONFIG += c++11

# Input
HEADERS += src/Neural/Network.hpp src/Neural/Node.hpp src/TrainingData.hpp
SOURCES += src/main.cpp \
           src/Neural/Network.cpp \
           src/Neural/Node.cpp \
		   src/TrainingData.cpp
